# Generated by Django 3.2 on 2021-08-13 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs', to=settings.AUTH_USER_MODEL),
        ),
    ]
