# Generated by Django 3.2 on 2021-08-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=30)),
                ('user_url', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='registe time')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPost',
            fields=[
                ('id', models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('post_time', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('body', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(null=True, upload_to='market/', verbose_name='썸네일')),
            ],
        ),
    ]
