# Generated by Django 3.2 on 2021-08-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpost',
            name='thumbnail',
            field=models.ImageField(upload_to='market/', verbose_name='썸네일'),
        ),
    ]
