# Generated by Django 3.2 on 2021-08-11 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='MarketPost_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='market.marketpost'),
        ),
    ]
