# Generated by Django 3.2 on 2021-08-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_marketpost_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpost',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='market/', verbose_name='썸네일'),
        ),
    ]
