# Generated by Django 3.2 on 2021-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='list/', verbose_name='사진')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='thumbnail/', verbose_name='썸네일')),
            ],
        ),
    ]
