# Generated by Django 3.2 on 2021-07-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='list/', verbose_name='사진'),
        ),
    ]
