# Generated by Django 3.2 on 2021-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210731_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
