# Generated by Django 3.2 on 2021-08-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='', verbose_name='썸네일'),
            preserve_default=False,
        ),
    ]
