# Generated by Django 3.2 on 2021-08-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20210803_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/', verbose_name='썸네일'),
        ),
    ]
