# Generated by Django 3.2 on 2021-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
