# Generated by Django 3.2 on 2021-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=30, null=True)),
                ('user_phone', models.CharField(max_length=30, null=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_account_name', models.CharField(max_length=20, null=True)),
                ('user_account', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
