# Generated by Django 3.2 on 2021-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cash',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='donate',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
