# Generated by Django 3.2 on 2021-08-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_userinfo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(default='static/img/original.png', upload_to='userinfo/'),
        ),
    ]
