# Generated by Django 3.2 on 2021-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_userinfo_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth',
            field=models.CharField(max_length=10, null=True, verbose_name='인증번호'),
        ),
    ]
