# Generated by Django 3.2 on 2021-08-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20210803_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='qua',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
