# Generated by Django 3.2 on 2021-08-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_alter_userinfo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_description',
            field=models.TextField(default='도외주세요!'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(default="{% static 'img/original.png' %}", upload_to='userinfo/'),
        ),
    ]
