# Generated by Django 3.2 on 2021-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20210810_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(upload_to='userinfo/'),
        ),
    ]
