# Generated by Django 3.2 on 2021-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_userinfo_qua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='donate',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qua',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
