# Generated by Django 3.2 on 2021-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_auto_20210804_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='give',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
