# Generated by Django 3.2 on 2021-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_userinfo_give'),
    ]

    operations = [
        migrations.CreateModel(
            name='whodonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whogetmoney', models.CharField(max_length=30, null=True)),
                ('givemoney', models.CharField(max_length=30, null=True)),
                ('whogivemoney', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='give',
        ),
    ]
