# Generated by Django 3.2 on 2021-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20210804_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='whodonate',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
