# Generated by Django 3.2 on 2021-08-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_photo1_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='thumbnail',
        ),
    ]
