# Generated by Django 3.2 on 2021-08-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0010_remove_post1_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Photo1',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
