# Generated by Django 3.2 on 2021-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_post1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='userinfo/', verbose_name='사진'),
        ),
    ]
