# Generated by Django 3.2 on 2021-08-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_alter_post_post_time'),
        ('user_info', '0014_alter_whodonate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='whodonate',
            name='what_post',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='list.post'),
            preserve_default=False,
        ),
    ]
