# Generated by Django 3.2 on 2021-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0015_whodonate_what_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
