# Generated by Django 3.2 on 2021-08-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0016_alter_userinfo_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(default='C:\\Users\\duddl\\OneDrive\\바탕 화면\\profileimage.jpg', upload_to='userinfo/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_nickname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
