# Generated by Django 3.2 on 2021-08-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0017_auto_20210806_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_totalcash',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
