# Generated by Django 3.2 on 2021-08-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0019_alter_userinfo_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_description',
            field=models.TextField(default='잘 부탁드립니다!!'),
        ),
    ]
