# Generated by Django 3.2 on 2021-08-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0020_userinfo_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(default='static/profileimage.jpg', upload_to='userinfo/'),
        ),
    ]
