# Generated by Django 3.2 on 2021-08-06 04:33

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0021_alter_userinfo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
    ]
