# Generated by Django 3.2 on 2021-08-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0022_alter_post1_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
