# Generated by Django 3.2 on 2021-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0023_alter_post1_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_totaldonate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
